-- MySQL Script generated by MySQL Workbench
-- Tue Aug 25 12:39:33 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Patient` (
  `PatientID` INT NOT NULL COMMENT '',
  `PatientName` MEDIUMTEXT NOT NULL COMMENT '',
  `PatientDateOfBirth` DATE NOT NULL COMMENT '',
  `PatientSex` TEXT(1) NOT NULL COMMENT '',
  `PatientSize` INT NOT NULL COMMENT '',
  `PatientWeight` INT NOT NULL COMMENT '',
  `typeOfPatientID` MEDIUMTEXT NOT NULL COMMENT '',
  `PatientAdress` MEDIUMTEXT NULL COMMENT '',
  `InsurancePlanIdentification` MEDIUMTEXT NULL COMMENT '',
  `ContryOfResidence` MEDIUMTEXT NOT NULL COMMENT '',
  `PatientTelephoneNumber` INT NULL COMMENT '',
  `AdditionalHistory` LONGTEXT NULL COMMENT '',
  PRIMARY KEY (`PatientID`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Examen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Examen` (
  `AccessionNumber` INT NOT NULL COMMENT '',
  `InstanceCreationDate` DATE NOT NULL COMMENT '',
  `InstanceCreationTime` TIME(10) NOT NULL COMMENT '',
  `ProcedureCodeSequence` MEDIUMTEXT NOT NULL COMMENT '',
  `InstitutionalDepartementName` MEDIUMTEXT NULL COMMENT '',
  `ProtocolName` MEDIUMTEXT NOT NULL COMMENT '',
  `AnatomicRegionSequence` MEDIUMTEXT NOT NULL COMMENT '',
  `AnatomicOrientationType` MEDIUMTEXT NOT NULL COMMENT '',
  `BodyPartExamined` MEDIUMTEXT NOT NULL COMMENT '',
  `PatientPosition` MEDIUMTEXT NOT NULL COMMENT '',
  `PerformedProcedureStepID` MEDIUMTEXT NOT NULL COMMENT '',
  `PerformedProcedureStepDescription` MEDIUMTEXT NOT NULL COMMENT '',
  `ContentDate` DATE NOT NULL COMMENT '',
  `ContentTime` TIME(10) NOT NULL COMMENT '',
  `InstanceCreatorUID` MEDIUMTEXT NOT NULL COMMENT '',
  PRIMARY KEY (`AccessionNumber`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Opérateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Opérateur` (
  `OperatorIDSequence` TEXT(2) NOT NULL COMMENT '',
  `OperatorName` MEDIUMTEXT NOT NULL COMMENT '',
  `Examen_AccessionNumber` INT NOT NULL COMMENT '',
  PRIMARY KEY (`OperatorIDSequence`)  COMMENT '',
  INDEX `fk_Opérateur_Examen1_idx` (`Examen_AccessionNumber` ASC)  COMMENT '',
  CONSTRAINT `fk_Opérateur_Examen1`
    FOREIGN KEY (`Examen_AccessionNumber`)
    REFERENCES `mydb`.`Examen` (`AccessionNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Realisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Realisateur` (
  `PerformingPhysicianIDSequence` TEXT(2) NOT NULL COMMENT '',
  `PerformingPhysicianName` MEDIUMTEXT NOT NULL COMMENT '',
  `Examen_AccessionNumber` INT NOT NULL COMMENT '',
  PRIMARY KEY (`PerformingPhysicianIDSequence`)  COMMENT '',
  INDEX `fk_Realisateur_Examen1_idx` (`Examen_AccessionNumber` ASC)  COMMENT '',
  CONSTRAINT `fk_Realisateur_Examen1`
    FOREIGN KEY (`Examen_AccessionNumber`)
    REFERENCES `mydb`.`Examen` (`AccessionNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Prescripteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Prescripteur` (
  `ReferringPhysicianIDSequence` TEXT(2) NOT NULL COMMENT '',
  `ReferringPhysicianName` MEDIUMTEXT NOT NULL COMMENT '',
  `Examen_AccessionNumber` INT NOT NULL COMMENT '',
  PRIMARY KEY (`ReferringPhysicianIDSequence`)  COMMENT '',
  INDEX `fk_Prescripteur_Examen1_idx` (`Examen_AccessionNumber` ASC)  COMMENT '',
  CONSTRAINT `fk_Prescripteur_Examen1`
    FOREIGN KEY (`Examen_AccessionNumber`)
    REFERENCES `mydb`.`Examen` (`AccessionNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Site`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Site` (
  `InstitutionName` MEDIUMTEXT NOT NULL COMMENT '',
  `InstitutionAdress` MEDIUMTEXT NOT NULL COMMENT '',
  PRIMARY KEY (`InstitutionName`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DICOM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DICOM` (
  `IP` MEDIUMTEXT NOT NULL COMMENT '',
  `Port` MEDIUMTEXT NOT NULL COMMENT '',
  `TransfertSyntaxeUID` MEDIUMTEXT NOT NULL COMMENT '',
  PRIMARY KEY (`IP`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produit` (
  `ImplementationVersionName` INT NOT NULL COMMENT '',
  `PrivateInformation` MEDIUMTEXT NULL COMMENT '',
  `SpecificCaractereSet` MEDIUMTEXT NOT NULL COMMENT '',
  `ImageType` MEDIUMTEXT NOT NULL COMMENT '',
  `Modality` TINYTEXT NOT NULL COMMENT '',
  `Manufacturer` MEDIUMTEXT NOT NULL COMMENT '',
  `ManufacturerModelName` MEDIUMTEXT NOT NULL COMMENT '',
  `SoftwareVersion` TINYTEXT NOT NULL COMMENT '',
  `DateOfLastCalibration` DATE NOT NULL COMMENT '',
  `TimeOfLastCalibration` TIME(10) NOT NULL COMMENT '',
  `ImplementationClassUID` MEDIUMTEXT NOT NULL COMMENT '',
  PRIMARY KEY (`ImplementationVersionName`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Console`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Console` (
  `SourceApplicationEntityTitle` MEDIUMTEXT NOT NULL COMMENT '',
  `StationName` MEDIUMTEXT NOT NULL COMMENT '',
  `DeviceSerialNumber` MEDIUMTEXT NOT NULL COMMENT '',
  `PerformedStationAETitle` MEDIUMTEXT NOT NULL COMMENT '',
  `PerformedStationName` MEDIUMTEXT NOT NULL COMMENT '',
  `DICOM_IP` MEDIUMTEXT NOT NULL COMMENT '',
  `Consolecol` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`SourceApplicationEntityTitle`, `DICOM_IP`)  COMMENT '',
  INDEX `fk_Console_DICOM1_idx` (`DICOM_IP` ASC)  COMMENT '',
  CONSTRAINT `fk_Console_DICOM1`
    FOREIGN KEY (`DICOM_IP`)
    REFERENCES `mydb`.`DICOM` (`IP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Study`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Study` (
  `StudyID` INT NOT NULL COMMENT '',
  `AquisitionsOnStudy` INT NOT NULL COMMENT '',
  `StudyDate` DATE NOT NULL COMMENT '',
  `StudyTime` TIME(10) NOT NULL COMMENT '',
  `ReferencedStudySequence` MEDIUMTEXT NOT NULL COMMENT '',
  PRIMARY KEY (`StudyID`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Serie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Serie` (
  `SeriesDescription` INT NOT NULL COMMENT '',
  `SeriesNumber` INT NOT NULL COMMENT '',
  `InstanceNumber` INT NOT NULL COMMENT '',
  `ImagesInAcquisition` INT NOT NULL COMMENT '',
  `SerieDate` DATE NOT NULL COMMENT '',
  `SerieTime` TIME(10) NOT NULL COMMENT '',
  `AcquisitionDate` DATE NOT NULL COMMENT '',
  `AcquisitionTime` TIME(10) NOT NULL COMMENT '',
  `SerieInstanceUID` MEDIUMTEXT NOT NULL COMMENT '',
  `FrameOfReferenceUID` MEDIUMTEXT NOT NULL COMMENT '',
  `MediaStorageSOPClassUID` MEDIUMTEXT NOT NULL COMMENT '',
  `SOPClassUID` MEDIUMTEXT NOT NULL COMMENT '',
  `ReferencedSOPClassUID` MEDIUMTEXT NOT NULL COMMENT '',
  `Study_StudyID` INT NOT NULL COMMENT '',
  PRIMARY KEY (`SeriesDescription`, `Study_StudyID`)  COMMENT '',
  INDEX `fk_Serie_Study1_idx` (`Study_StudyID` ASC)  COMMENT '',
  CONSTRAINT `fk_Serie_Study1`
    FOREIGN KEY (`Study_StudyID`)
    REFERENCES `mydb`.`Study` (`StudyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Image` (
  `Reference` INT NOT NULL COMMENT '',
  `SampelPerPixel` INT NOT NULL COMMENT '',
  `SampelPerPixelUsed` INT NOT NULL COMMENT '',
  `PhotometricInterpretation` MEDIUMTEXT NOT NULL COMMENT '',
  `Rows` INT NOT NULL COMMENT '',
  `Columns` INT NOT NULL COMMENT '',
  `BitAllocated` INT NOT NULL COMMENT '',
  `BitStoraged` INT NOT NULL COMMENT '',
  `PixelRepresentation` INT NOT NULL COMMENT '',
  `WindowCenter` INT NOT NULL COMMENT '',
  `WindowWith` INT NOT NULL COMMENT '',
  `WaveformDisplayBkgCIELabValue` MEDIUMTEXT NOT NULL COMMENT '',
  `ChannelRecommendDisplayCIELabValue` MEDIUMTEXT NOT NULL COMMENT '',
  `NumericValue` INT NOT NULL COMMENT '',
  `ImageFrameOrigin` INT NOT NULL COMMENT '',
  `AnnotationSequence` MEDIUMTEXT NULL COMMENT '',
  `UnformattedTextValue` MEDIUMTEXT NULL COMMENT '',
  `GraphicLayerDescription` MEDIUMTEXT NULL COMMENT '',
  `OverlayRows` INT NOT NULL COMMENT '',
  `OverlayColumns` INT NOT NULL COMMENT '',
  `OverlayDescription` MEDIUMTEXT NOT NULL COMMENT '',
  `OverlayType` TEXT(1) NOT NULL COMMENT '',
  `OverlayOrigin` TEXT(3) NOT NULL COMMENT '',
  `OverlayBitsAllocated` INT NOT NULL COMMENT '',
  `OverlayBitPosition` INT NOT NULL COMMENT '',
  `OverlayData` INT NOT NULL COMMENT '',
  `PixelData` INT NOT NULL COMMENT '',
  `ReferencedImageSequence` MEDIUMTEXT NOT NULL COMMENT '',
  `MediaStorageSOPInstanceUID` MEDIUMTEXT NOT NULL COMMENT '',
  `SOPInstanceUID` MEDIUMTEXT NOT NULL COMMENT '',
  `ReferencedSOPInstanceUID` MEDIUMTEXT NOT NULL COMMENT '',
  `Serie_SeriesDescription` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Reference`, `Serie_SeriesDescription`)  COMMENT '',
  INDEX `fk_Image_Serie_idx` (`Serie_SeriesDescription` ASC)  COMMENT '',
  CONSTRAINT `fk_Image_Serie`
    FOREIGN KEY (`Serie_SeriesDescription`)
    REFERENCES `mydb`.`Serie` (`SeriesDescription`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Signal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Signal` (
  `WaveformOriginality` INT NOT NULL COMMENT '',
  `NumberOfWaveformChannel` INT NOT NULL COMMENT '',
  `NumberOfWaveformSamples` INT NOT NULL COMMENT '',
  `SamplingFrequency` INT NOT NULL COMMENT '',
  `ChannelDefinitionSequence` TINYTEXT NOT NULL COMMENT '',
  `WaveformChannelNumber` INT NOT NULL COMMENT '',
  `ChannelLabel` MEDIUMTEXT NOT NULL COMMENT '',
  `ChannelStatut` TINYTEXT NOT NULL COMMENT '',
  `ChannelSourcesSequence` MEDIUMTEXT NOT NULL COMMENT '',
  `ChannelSensitivityCorrection` INT NULL COMMENT '',
  `ChannelBaseline` INT NULL COMMENT '',
  `ChannelOfset` TIME(10) NOT NULL COMMENT '',
  `WaveformBitStored` INT NOT NULL COMMENT '',
  `NotchFilterBandwitdh` INT NULL COMMENT '',
  `MeasurementUnit` TINYTEXT NOT NULL COMMENT '',
  `WaveformSequence` MEDIUMTEXT NOT NULL COMMENT '',
  PRIMARY KEY (`WaveformOriginality`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Patient_has_Examen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Patient_has_Examen` (
  `Patient_PatientID` INT NOT NULL COMMENT '',
  `Examen_AccessionNumber` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Patient_PatientID`, `Examen_AccessionNumber`)  COMMENT '',
  INDEX `fk_Patient_has_Examen_Examen1_idx` (`Examen_AccessionNumber` ASC)  COMMENT '',
  INDEX `fk_Patient_has_Examen_Patient1_idx` (`Patient_PatientID` ASC)  COMMENT '',
  CONSTRAINT `fk_Patient_has_Examen_Patient1`
    FOREIGN KEY (`Patient_PatientID`)
    REFERENCES `mydb`.`Patient` (`PatientID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Patient_has_Examen_Examen1`
    FOREIGN KEY (`Examen_AccessionNumber`)
    REFERENCES `mydb`.`Examen` (`AccessionNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
